# Generated by Django 4.2.2 on 2023-07-13 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='cat',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='status',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.AddField(
            model_name='announcement',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cats', to='board.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='comment',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='board_categ_name_338ed0_idx'),
        ),
    ]
