# Generated by Django 4.2.2 on 2023-07-13 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_announcement_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='name',
        ),
    ]
